/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PAPERSERVER_H_RPCGEN
#define _PAPERSERVER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct add_article_in {
	char *author;
	char *title;
	char *file_name;
};
typedef struct add_article_in add_article_in;

struct list_article_out {
	long num;
	char *author;
	char *title;
	struct list_article_out *next;
};
typedef struct list_article_out list_article_out;

struct article_info_out {
	char *author;
	char *title;
};
typedef struct article_info_out article_info_out;

typedef long article_num;

#define PAPERSERVER_PROG 0x20004321
#define PAPERSERVER_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADD 1
extern  article_num * add_1(add_article_in *, CLIENT *);
extern  article_num * add_1_svc(add_article_in *, struct svc_req *);
#define LIST 2
extern  list_article_out * list_1(void *, CLIENT *);
extern  list_article_out * list_1_svc(void *, struct svc_req *);
#define INFO 3
extern  article_info_out * info_1(article_num *, CLIENT *);
extern  article_info_out * info_1_svc(article_num *, struct svc_req *);
#define REMOVE 4
extern  int * remove_1(article_num *, CLIENT *);
extern  int * remove_1_svc(article_num *, struct svc_req *);
extern int paperserver_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADD 1
extern  article_num * add_1();
extern  article_num * add_1_svc();
#define LIST 2
extern  list_article_out * list_1();
extern  list_article_out * list_1_svc();
#define INFO 3
extern  article_info_out * info_1();
extern  article_info_out * info_1_svc();
#define REMOVE 4
extern  int * remove_1();
extern  int * remove_1_svc();
extern int paperserver_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_add_article_in (XDR *, add_article_in*);
extern  bool_t xdr_list_article_out (XDR *, list_article_out*);
extern  bool_t xdr_article_info_out (XDR *, article_info_out*);
extern  bool_t xdr_article_num (XDR *, article_num*);

#else /* K&R C */
extern bool_t xdr_add_article_in ();
extern bool_t xdr_list_article_out ();
extern bool_t xdr_article_info_out ();
extern bool_t xdr_article_num ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PAPERSERVER_H_RPCGEN */
